(defun main ()
  (let ((s (read-string ""))
        (cnt 0))
    (dotimes (i (length s))
      (cond ((char-equal (aref s i) ?v)
              (setq cnt (+ cnt 1))
              )
            ((char-equal (aref s i) ?w)
              (setq cnt (+ cnt 2))
              )
        )
      )
    (princ cnt)
    (terpri)
    )
  nil
  )

(main)
